### ISSUE TITLE
DBC Parsing error: double_val

### ISSUE THREAD

**Issue by dsantxez** [ihedvall/dbclib#10]
I have started using this project for a personal project and I have come across the following problem.

If I define any double number for the scale, offset, etc. of a signal, the parser will remove the digits after the floating point. For example and scale of 0.1 will be parsed as 0 or an offset of 10.5 will be parsed as 10.

I have checked the regular expression file and I don't see anything wrong in there, although I don't use bison and flex for parsing.

I will continue with tests and see if I can check the error, maybe familiarize with flex and bison a bit better.
[proba.txt](https://github.com/user-attachments/files/17401599/proba.txt)

The txt file is actually a dbc file but I had to change the extension to upload it here. This is the file that I have been testing with.

Thank you for your time

**Comment by dsantxez** [comment]
Ok, I have double checked just in case and I the dbcviewer the scale and so forth are viewed correctly, so I'm doing something wrong definetly.

My code is something like this:

```
dbc::DbcFile file;
file.Filename(dbcPath.u8string());
if(file.ParseFile()==false)
{
    return false;
}

return true;
```

This is how I create the dbcfile handle. In here, inside parseFile I already see the scale with the digits cropped. I will check how it is done at  dbcviewer and compare with this approach.

**Comment by ihedvall** [comment]
I can do a simple test but the DbcViewer use the above approach of parsing. I do some testing with your file. Note that the library have function for parsing the CAN data bytes to signal values as well.

**Comment by ihedvall** [comment]
@dsantxez 
The DBC file describes a CAN Network so after you parse the file, you should call the 
```cpp
const auto* network =  file.GetNetwork();
for (const auto& [message_name,message] : network->Messages() {
  // Do something with signals.
} 
```
You are on the wrong path if you need to go into the flex/bison somehow.

**Comment by dsantxez** [comment]
I Will make an example app and link it with the DBC library.

The code snippet I showed is part of a bigger code, but I do as you said. I'll do some testing tomorrow and let you know.

Thank you for the quick reply

**Comment by dsantxez** [comment]
I have done some more testing and this are the results:

If I link the dbc library to my main program, then the Scale, offset and so on are parsed correctly. If I link the dbc library to another library and then use that second library with the main program, that's when the error happens. I will see why is that happening. I don't know if you have encountered anything like this.

Maybe I'm guessing it is because of the linking order, or something like that. I will experiment some more and see if I can shed some light on this issue.

**Comment by dsantxez** [comment]
Ok, I have found why the error is happening.

The program I'm making uses gettext for translation purposes and before starting it reads the locale of the system to bind the translations to the system language.

 // Set locale and translation stuff
    char* s = setlocale(LC_ALL, "");
    bindtextdomain("project",std::filesystem::current_path().u8string().c_str());
    textdomain("project");

If I create the DBC file before this lines, it works as it is supposed to. I have tested more and I see that it is related to the setlocale function. Maybe it changes the . , notation for numbers or something like that and that is why the parsing error. I will see how can I change this call and I can still keep using the gettext library.

Thank you for your time and great library!

**Comment by ihedvall** [comment]
@dsantxez 
This is a not so uncommon problem in C++. It might be better to take one step back and accept that this is a much simpler problem than you think. I don't know what is the problem but C++ libraries doesn't use the linker only executable (and DLL) uses the linker. Your executable shall link both your lib and the DBC lib.

1. Mixing different compile option (MT, static or dynamic). The linker normally complains.
2. Bad or more correctly, the same naming of the functions. What Scale() and Offset() function am I running?
3. Once in my project, the linker took one MinGW library and linked it to a MSVC exeutable. That work just with a minor warning. The execution didn't go well.  
4. According to some rule, a colleague programmer will figure out the error within one minute. 

Good Hunting
Ingemar Hedvall

**Comment by ihedvall** [comment]
The floating point text value must use dot "10.9" not "10,9". I will add a unit test to check that the flex text to float conversion not is dependent on the computer locale. The older C function doesn't while the newer C++>11 do.

**Comment by ihedvall** [comment]
@dsantxez 
I added a small bug to fix so we don't get this problem in the future. 

I can add writing of DBC files to the library if you want it.

**Comment by dsantxez** [comment]
Thank you @ihedvall, without the setLocale function the project is working right now as intended.

dbclib->library1->main_project. I have to check more about the setLocale method. If I don't call it, gettext will work, however, I loose the capability of changing my programs language on the go.

I will keep investigating, still, the parsing of the DBC file and the parsing of online can frames is working like a charm.

**Comment by ihedvall** [comment]
@dsantxez 
In the dbcflexer.l file:
```c

{double_val}     {
                   double temp = 0.0;
                   try {
                     temp = std::stod(yytext);
                   } catch (const std::exception&) {

                   }
                   yylval->build<double>(temp);
                   return token::DOUBLE_VAL;
                 }
```

The std::stod() function is dependent on the locale decimal point character.
If you google string to float conversion C++, there is a lot of different solutions. I test atof() or something similar tomorrow.

If you using the built-in parsing of CAN frames, there is 2 ways you may parse CAN frames to signal values. The simplest is one frame to signal value or you may use an observer cache. The latter also parses CAN signal that are larger than 8 bytes typical diagnostic messages.

**Comment by dsantxez** [comment]
Just out of curiosity, does this library parse Can FD Messages? Because this messages need to be read/sent differently to Can2.0 message and the size can be up to 64 bytes

BTW,
https://en.cppreference.com/w/cpp/utility/from_chars

This function was included with c++17 and is locale agnostic

**Comment by ihedvall** [comment]
@dsantxez 
Well this is little bit of my problem. I don't have any CAN equipment to test against. I have a handful of matching DBC and MDF bus log files. None of them uses CANFD. To make it worse, there are at least 4 CAN protocols that handles the conversion differently. 

The DBC message to signal may work with CANFD. You can select the bus type and protocol separately, in the DbcNetwork class but many DBC files doesn't define neither bus nor protocol.

If you have a DBC/FD file and some CANFD frames, you "CAN" test and check if it works. I think the DBC parsing should work with CANFD.

**Comment by ihedvall** [comment]
@dsantxez 
I have fixed so the double scale, offset, min and max limits are independent of the locale type. I fixed some minor Bus Type for CAN FD. The parser seems to work on CAN FD DBC files. I cannot test the  DbcFile::ParseMessage() function with CAN FD but there shouldn't be any major problem.
[CAN FD DBC Requirements](https://rtahotline.etas.com/confluence/display/RH/Importing+CAN-FD+Signals+with+a+dbc+file)

**Comment by dsantxez** [comment]
I have test the ParseMessage with CAN FD frames and I don't know why but if the CAN Fd uses extended meesage IDs the code would fail in `GetMessageByCanId` of the Network class. It returns nullptr and thus it does not translate. However, chaging the code to this:

`auto it = message_list_.find(can_id);`
 ` if(it==message_list_.end())`
 ` {`
 ` return nullptr;`
 ` }`
 ` return &it->second;`

This code works. I have seen the the key of the map is the message id. Nevertheless, both codes do the same thing at first glance so I don't know why one is failing and the other one is not.

With this change, the parsing works like a charm. I have tested it using virtual can in linux btw, really helpful toolset to test CAN communications

**Comment by ihedvall** [comment]
In the DBC file,  the Message ID = CAN ID + Extended Address Flag. The CAN ID is in the lower 29 bits while the extended address bit while the Extended Address flag is in bit 31. There should be a difference between GetMessage(message ID) and GetMessageByCanId(CAN ID). In theory, you can mix 11-bit and 29-bit addresses on a DBC Network.

My proposal is to mask out the extended bit from the GetxxByCanId() call. You could use a message ID as input argument. You may temporary test it with the below code. 


```c++
Message* Network::GetMessageByCanId(uint64_t can_id) {
  constexpr uint64_t kMaxExtendedId = 0x1FFFFFFFULL; ///< Max Extended CAN ID
  can_id &= kMaxExtendedId;
  auto itr = std::find_if(message_list_.begin(),
                          message_list_.end(),
                          [&] (const MessageList ::value_type &mess) {
    return mess.second.CanId() == can_id;
  });
  return itr != message_list_.end() ? &itr->second : nullptr;
}
```

There are several GetxxxByCanId so I need to mask out the bits little bit everywhere.

**Comment by ihedvall** [comment]
@dsantxez 
I have fixed the CAN vs Message ID problem. You may give it a go.

**Comment by dsantxez** [comment]
It works! It's been crazy at work, so sorry for the late reply.

The initial prototype of the app is working like a charm. The parsing is really efficient and the toll it takes at the cpu level is really low even with heavy messaging in CAN ( I Have tested it with real HW at real situation (Heavy duty vehicle)

Thank you for your help

**Comment by ihedvall** [comment]
@dsantxez 
I have looked closer to code around the parsing part and found a couple of issues. I think that the parsing works for plain DBC messages but depending on the protocol (ProtocolType) there exist DBC messages that span over more than one CAN(FD) message. How this work is dependent on the protocol. You may compare the DbcFile::ParseJ1939 and DbcFile::ParseNMEA2000 functions.

I found the following issues.

1. The DbcMessage support class should use DBC message ID instead of CAN Id.    
2. The NMEA 2000 parser needs to be adapted to CAN-FD. 
3. The J1939 has similar problem if DBC and CAN message sizes differs.
4. The OBD2 protocol is not tested. Similar problem as J1939.
5. There exist one protocol for agriculture vehicle but the specification is closed. 

I will add these issues to the GitHub repository.
