### ISSUE TITLE
Fixing CI build

### ISSUE THREAD

**Issue by Murmele** [ihedvall/dbclib#4]
with flex 2.6.4 it works without any problems.

CI:
`flex 2.5.4`

```
cd /home/runner/work/dbclib/dbclib/build/release && /usr/bin/flex -o/home/runner/work/dbclib/dbclib/src/dbcflexer.cpp /home/runner/work/dbclib/dbclib/src/dbcflexer.l
"/home/runner/work/dbclib/dbclib/src/dbcflexer.l", line 1: unrecognized '%' directive
```

**Comment by ihedvall** [comment]
Yes, that's what I'm using in Windows. 

It is the %top command that seems to be missing. in version 2.5. There seems to be some other commands also missing in that version. 

Update to 2.6 version or go back with flex version?

**Comment by Murmele** [comment]
I am using 2.6.4 and it works without any problems. The CI is using 2.5.4 and this makes problems.

**Comment by Murmele** [comment]
Shall we introduce an option to disable building the files even if flex is found?

**Comment by Murmele** [comment]
Is it this flex: https://github.com/westes/flex ? The version 2.5.4 ist from 1996

**Comment by Murmele** [comment]
https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=flex
according to this, unbuntu 22.04 uses also 2.6.4

In the CI: 
```
# flex-old contains FlexLexer.h which is needed by util
# For some reason, flex does not contain this header
sudo apt install --yes git cmake libboost-all-dev expat zlib1g flex-old
```

**Comment by Murmele** [comment]
Is it possible to remove those lines somehow?

```
#line 1 "D:/projects/dbclib/src/dbcflexer.cpp"
    #include <cstdint>

#line 4 "D:/projects/dbclib/src/dbcflexer.cpp"
```

**Comment by ihedvall** [comment]
I have solved the flex problem by adding the libfl-dev and removing the flex-old (2.5) to the linux build. It is a bug in the flex install regarding the flexlexer.h include file.

The build now works with just our favorite install failure.

**Comment by Murmele** [comment]
thank you I have seen thank you! I will check for the install. The problem is this FILE_SET. I am working on it
