### ISSUE TITLE
MakeAndRegisterTestInfo LNK2019

### ISSUE THREAD

**Issue by liurunjieuk** [ihedvall/dbclib#9]
MakeAndRegisterTestInfo LNK2019 when build with msvc 2019 win32 via vcpkg and cmake

**Comment by liurunjieuk** [comment]
in dbclib\script\googletest.cmake 
```
you must change the 'GIT_TAG HEAD' to 'GIT_TAG v1.12.0'
```

**Comment by ihedvall** [comment]
I think the error is that google test is included in the VCPKG build but Google test is always built from scratch (by FetchContent). Need to remove some lines in CMakeList.txt and vcpkg.json. I can do the change.

**Comment by ihedvall** [comment]
I have fixed the linkage problem in VC2022 and Win64. Hopefully this fix will work for VC2019 and Win32. It would be nice if you could verify the above fixes on your build system.
